### ISSUE TITLE
Proposal on how to represent 'No data' value in details column in the data revolution tables

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub-cms#16]
In the data revolution tables we have a column named ```details``` that  has years represented as integers. 
For rows where there is no year , a value of ```no data``` is used. How about we use ```-1``` or ```0``` to represent ```no data``` so that the detail column is purely of type Integer

**Comment by dw8547** [comment]
@epicallan, may it be `NULL`?

**Comment by epicallan** [comment]
@dw8547 NULL is fine.

**Comment by dw8547** [comment]
@epicallan, this won't work due to entries like:

1) `2010 (planned for 2016)`
2) `2014-2015`

etc.

Leaving column data type as `CHARACTER VARYING` in all `data_revolution` tables.
