### ISSUE TITLE
Duplicate colour values

### ISSUE THREAD

**Issue by dw8547** [devinit/datahub-cms#19]
There are duplicate colour values in [colours.csv](https://github.com/devinit/datahub-cms/blob/master/global/colors.csv):

1) [`green-dark`](https://github.com/devinit/datahub-cms/blob/master/global/colors.csv#L36) #007851
2) [`green-darker`](https://github.com/devinit/datahub-cms/blob/master/global/colors.csv#L37) #007851

As is, the data cannot be read into a table as we need unique hex colour values. Please advise.

**Comment by epicallan** [comment]
They shouldn't be the same will make a correction today.

**Comment by epicallan** [comment]
This error was picked from the brand book green colour pallet

<img width="940" alt="screen shot 2017-07-20 at 10 57 57" src="https://user-images.githubusercontent.com/6281527/28406755-6fd714a0-6d3a-11e7-85e2-5e95b20c642b.png">

correct values are as below
green-dark --> #14805c
green-darker  --> #09513a

**Comment by dw8547** [comment]
@epicallan, thank you. @RebeccaHills FYI, see above regarding error in brand book green colour pallet.

**Comment by RebeccaHills** [comment]
Thanks @epicallan 

We have a revised brand book actually, which states the darker green is #065139. Please use this.
