### ISSUE TITLE
Set value to NULL for countries that should not show in P20 maps 

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub-cms#21]
Countries like USA shouldn't show in this map, they currently show coz they have a value of zero. If they were sent to NULL they wouldn't show.

This is for ```data_series.percent_in_p20_national``` && ```data_series.poorest_20_percent```

I think @akmiller01 should avail new data files to @dw8547 .

![screen shot 2017-07-31 at 10 56 06](https://user-images.githubusercontent.com/6281527/28768074-fa32928a-75de-11e7-97a8-0c91cfa7df98.png)

**Comment by dw8547** [comment]
@epicallan & @akmiller01 alternatively provide list of countries to remove from table.

**Comment by akmiller01** [comment]
Hi Allan,

I believe that without exception, all countries with zero poverty can be removed. It's only at the subnational level that zero-poverty values are valid.

**Comment by dw8547** [comment]
`NULL`ifying in `data_series.poorest_20_percent`:
```
 di_id | year | value 
-------+------+-------
 BY    | 2013 |     0
 BY    | 2014 |     0
 BY    | 2015 |     0
(3 rows)
```
`NULL`ifying in `data_series.percent_in_p20_national`:
```
 di_id | year | value 
-------+------+-------
 AT    | 2013 |  0.00
 AU    | 2013 |  0.00
 BE    | 2013 |  0.00
 BY    | 2013 |  0.00
 CA    | 2013 |  0.00
 CH    | 2013 |  0.00
 CY    | 2013 |  0.00
 DE    | 2013 |  0.00
 DK    | 2013 |  0.00
 ES    | 2013 |  0.00
 FI    | 2013 |  0.00
 FR    | 2013 |  0.00
 GB    | 2013 |  0.00
 GL    | 2013 |  0.00
 GR    | 2013 |  0.00
 IE    | 2013 |  0.00
 IL    | 2013 |  0.00
 IS    | 2013 |  0.00
 IT    | 2013 |  0.00
 JO    | 2013 |  0.00
 JP    | 2013 |  0.00
 LU    | 2013 |  0.00
 NL    | 2013 |  0.00
 NO    | 2013 |  0.00
 PS    | 2013 |  0.00
 PT    | 2013 |  0.00
 RU    | 2013 |  0.00
 SE    | 2013 |  0.00
 SG    | 2013 |  0.00
 US    | 2013 |  0.00
(30 rows)
```

**Comment by dw8547** [comment]
Live.
