### ISSUE TITLE
What's the source of data for "What is the total revenue of x?" chart, digital recipient profile?

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub-cms#5]

**Comment by dw8547** [comment]
@epicallan, which section of the DH?

**Comment by dw8547** [comment]
I have the following:

database | schema | data_hub_tab | data_hub_visualisation | table
-------------|-----------|-------------------|--------------------------------|-------
ddw|digital_profile|recipient_country_profile|Government finance: What is the total revenue of x?|domestic
ddw|digital_profile|recipient_country_profile|Government finance: What is the total revenue of x?|warehouse/fact/gdp_usd_2015

**Comment by epicallan** [comment]
hi @dw8547 

Both the figures in the domestic and GDP table are ways of getting this value, my question is which table do we use. The code in the current live datahub wasn't clear in some way about which table to use, as if it had errors. Thats why this issue is here.

cc @BeckyWillmoth @kb4777

**Comment by dw8547** [comment]
@epicallan, the analysts were to clarify this in January but I don't recall hearing back on the issue so don't know now. Will chase.

**Comment by dw8547** [comment]
@epicallan, the metadata in the web app indicates that we settled for `domestic.csv`.

**Comment by epicallan** [comment]
cool thanks @dw8547
